##
## EPITECH PROJECT, 2022
## B-OOP-400-PAR-4-1-arcade-quentin.bourgeois
## File description:
## Makefile
##

all:	PACMAN NIBBLER

PACMAN:
	make -sC Pacman/

NIBBLER:
	make -sC Nibbler/

clean:
	make -sC Pacman/ clean
	make -sC Nibbler/ clean

fclean: clean

re: fclean all